# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.cache/wt [current_project]
set_property parent.project_path C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_output_repo c:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/B_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_ECSR_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_Fence_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_JALR_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_L_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_R_Word_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/I_R_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/Initial_Decoder.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/J_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/R_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/R_word_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/S_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/U_LUI_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/U_AUIPC_component.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/RISC_V_Decoder_Top.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/ScanRegister_Input.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/new/ScanRegister_Output.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_P.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_BYPASS.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_FSM.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_IR_DECODER.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_IR_UNIT.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TDO_MUX.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/TAP_TOP.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/imports/new/shift_reg_internal.vhd
  C:/Users/Public/Downloads/Top_Level_Design/Top_Level_Design.srcs/sources_1/new/Top_Level_Design.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Top_Level_Design -part xc7z010clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Top_Level_Design.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Top_Level_Design_utilization_synth.rpt -pb Top_Level_Design_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
